# Generated by Django 2.2.5 on 2019-09-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20190908_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
